"""dodanie_emaila_do_ucznia

Revision ID: 43e5d3e556ee
Revises: 7f24d620fc5f
Create Date: 2026-05-27 04:33:58.333882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '43e5d3e556ee'
down_revision: Union[str, Sequence[str], None] = '7f24d620fc5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uczen', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), server_default='brak@mail.com', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uczen', 'email')
    # ### end Alembic commands ###
